import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CatsProvider } from "@/hooks/CatsProvider";
import { WalletConnectProvider } from "@/hooks/WalletConnectProvider";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const bebasNueue = localFont({
  src: "./fonts/BebasNeue-Regular.woff",
  variable: "--font-bebas-nueue",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Clowder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bebasNueue.variable} antialiased`}
      >
        <Toaster />
        <CatsProvider>
          <WalletConnectProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </WalletConnectProvider>
        </CatsProvider>
      </body>
    </html>
  );
}
